/*
 * Stable registry of icon names so pages reference `icons.MUSIC` instead of
 * importing a FontAwesome module directly. Mirrors Sonarr's `Helpers/Props/Icons.ts`.
 */
import {
  faArchive,
  faArrowLeft,
  faArrowRight,
  faBan,
  faBars,
  faBell,
  faBolt,
  faBookmark,
  faBug,
  faCalendar,
  faCheck,
  faCheckCircle,
  faChevronCircleDown,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faClock,
  faCloud,
  faCloudDownloadAlt,
  faCog,
  faCogs,
  faCopy,
  faDownload,
  faEllipsisH,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFilm,
  faFilter,
  faFolder,
  faFolderOpen,
  faHandPaper,
  faHeart,
  faHome,
  faInfoCircle,
  faKey,
  faList,
  faLock,
  faMagic,
  faMagnet,
  faMusic,
  faPause,
  faPlay,
  faPlus,
  faQuestionCircle,
  faRefresh,
  faRetweet,
  faSearch,
  faServer,
  faSignOutAlt,
  faSpinner,
  faStar,
  faStarHalfAlt,
  faStream,
  faSyncAlt,
  faTable,
  faTags,
  faThList,
  faThumbsDown,
  faThumbsUp,
  faTimes,
  faTimesCircle,
  faToolbox,
  faTrash,
  faTrashAlt,
  faTv,
  faUnlock,
  faUser,
  faUserCircle,
  faVideo,
  faWrench,
} from "@fortawesome/free-solid-svg-icons";

export const icons = {
  ACTIVITY: faRetweet,
  ADD: faPlus,
  ALERT: faExclamationCircle,
  ARCHIVE: faArchive,
  ARROW_LEFT: faArrowLeft,
  ARROW_RIGHT: faArrowRight,
  BACKUP: faArchive,
  BAN: faBan,
  BARS: faBars,
  BELL: faBell,
  BOOKMARK: faBookmark,
  BUG: faBug,
  CALENDAR: faCalendar,
  CHECK: faCheck,
  CHECK_CIRCLE: faCheckCircle,
  CHEVRON_DOWN: faChevronDown,
  CHEVRON_LEFT: faChevronLeft,
  CHEVRON_RIGHT: faChevronRight,
  CHEVRON_UP: faChevronUp,
  CHEVRON_CIRCLE_DOWN: faChevronCircleDown,
  CIRCLE: faCircle,
  CLOCK: faClock,
  CLONE: faCopy,
  CLOUD: faCloud,
  COG: faCog,
  COGS: faCogs,
  COPY: faCopy,
  DANGER: faExclamationCircle,
  DELETE: faTrashAlt,
  DOWNLOAD: faDownload,
  DOWNLOADED: faCheckCircle,
  DOWNLOADING: faCloudDownloadAlt,
  EDIT: faWrench,
  ELLIPSIS: faEllipsisH,
  EXTERNAL_LINK: faExternalLinkAlt,
  EYE: faEye,
  EYE_SLASH: faEyeSlash,
  FATAL: faTimesCircle,
  FILM: faFilm,
  FILTER: faFilter,
  FOLDER: faFolder,
  FOLDER_OPEN: faFolderOpen,
  HEALTH: faHeart,
  HEART: faHeart,
  HOME: faHome,
  INFO: faInfoCircle,
  INTERACTIVE: faMagic,
  KEY: faKey,
  LIBRARY: faMusic,
  LIST: faList,
  LOCK: faLock,
  LOGOUT: faSignOutAlt,
  MAGNET: faMagnet,
  MISSING: faExclamationTriangle,
  MONITORED: faBookmark,
  MUSIC: faMusic,
  NOTIFICATIONS: faBell,
  PAUSE: faPause,
  PLAY: faPlay,
  POSTERS: faThList,
  QUESTION: faQuestionCircle,
  QUICK: faBolt,
  REFRESH: faSyncAlt,
  REMOVE: faTimes,
  RESTART: faRefresh,
  RIGHT_DIR: faChevronRight,
  RSS: faStream,
  SAVE: faCheck,
  SEARCH: faSearch,
  SETTINGS: faCog,
  SPINNER: faSpinner,
  STAR: faStar,
  STAR_FILLED: faStar,
  STAR_HALF: faStarHalfAlt,
  STATUS: faToolbox,
  SUCCESS: faCheckCircle,
  SYNC: faSyncAlt,
  SYSTEM: faServer,
  TABLE: faTable,
  TAGS: faTags,
  TIME: faClock,
  THUMBS_DOWN: faThumbsDown,
  THUMBS_UP: faThumbsUp,
  TRASH: faTrash,
  TV: faTv,
  UNMONITORED: faBookmark,
  UNLOCK: faUnlock,
  USER: faUser,
  USER_CIRCLE: faUserCircle,
  VIDEO: faVideo,
  WANTED: faHandPaper,
  WARNING: faExclamationTriangle,
  WORKING: faSpinner,
};

export type IconName = keyof typeof icons;
