<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Vidarr.Api\Vidarr.Api.csproj" />
    <ProjectReference Include="..\..\src\Vidarr.EventBus\Vidarr.EventBus.csproj" />
    <ProjectReference Include="..\..\src\Vidarr.Health\Vidarr.Health.csproj" />
    <ProjectReference Include="..\..\src\Vidarr.Backup\Vidarr.Backup.csproj" />
    <ProjectReference Include="..\..\src\Vidarr.Catalog\Vidarr.Catalog.csproj" />
    <ProjectReference Include="..\..\src\Vidarr.DownloadClients\Vidarr.DownloadClients.csproj" />
    <ProjectReference Include="..\..\src\Vidarr.Indexers\Vidarr.Indexers.csproj" />
    <ProjectReference Include="..\..\src\Vidarr.Rules\Vidarr.Rules.csproj" />
    <ProjectReference Include="..\..\src\Vidarr.Scheduler\Vidarr.Scheduler.csproj" />
    <ProjectReference Include="..\Vidarr.Tests.Common\Vidarr.Tests.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

</Project>
